devices([
  "iPhone SE",
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone 11",
  "iPhone 11 Pro"
])

languages([
  "en-US",
  "de-DE"
])

# Enable the following launch arguments to test dynamic type 

# launch_arguments([
#   "-UIPreferredContentSizeCategoryName UICTContentSizeCategoryAccessibilityL",
#   "-UIPreferredContentSizeCategoryName UICTContentSizeCategoryL"
# ])

clear_previous_screenshots true
