devices([
  "iPhone 5s",
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone X",
  "iPhone Xs Max"
])

languages([
  "en-US",
  "de-DE"
])

# Enable the following launch arguments to test dynamic type 

# launch_arguments([
#   "-UIPreferredContentSizeCategoryName UICTContentSizeCategoryAccessibilityL",
#   "-UIPreferredContentSizeCategoryName UICTContentSizeCategoryL"
# ])

clear_previous_screenshots true
